### ISSUE TITLE
[バグ]rake db:seed がエラー

### ISSUE THREAD

**Issue by ms2sato** [shuheiktgw/todo_list#21]
```
(prevent_multiple_registration) $ bin/rake db:seed
Running via Spring preloader in process 84776
rake aborted!
SyntaxError: /Users/ms2/dev/work/training/kitagawa/db/seeds.rb:5: syntax error, unexpected keyword_end, expecting ')'
/Users/ms2/dev/work/training/kitagawa/db/seeds.rb:18: syntax error, unexpected end-of-input, expecting keyword_end
/Users/ms2/dev/work/training/kitagawa/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/Users/ms2/dev/work/training/kitagawa/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `block in load'
/Users/ms2/dev/work/training/kitagawa/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/ms2/dev/work/training/kitagawa/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/Users/ms2/dev/work/training/kitagawa/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/engine.rb:547:in `load_seed'
/Users/ms2/dev/work/training/kitagawa/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/Users/ms2/dev/work/training/kitagawa/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.2/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
/Users/ms2/dev/work/training/kitagawa/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/Users/ms2/dev/work/training/kitagawa/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `block in load'
/Users/ms2/dev/work/training/kitagawa/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/ms2/dev/work/training/kitagawa/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

**Comment by shuheiktgw** [comment]
あー,これ小さいバグなんでそのままmaster修正してしまいます!
